version: "3.5"
services:
  postgresdb:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./script/init/1-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./script/init/2-data.sql:/docker-entrypoint-initdb.d/2-data.sql
